### ISSUE TITLE
How to use `npm i` to add a local dependency for a package?

### ISSUE THREAD

**Issue by ylc395** [Quramy/npm-ts-workspaces-example#15]
For example, if we are in `packages/x-cli/`, and wants to add a dependecy(which is in another workspace, such as `@quramy/x-core`) for it, which npm command should we use? Using `npm i @quramy/x-core` will get a "not found" error, since this packages haven't been publish yet.

**Comment by Quramy** [comment]
We should edit package/x-cli/package.json . I don't know other way :sob:

**Comment by ylc395** [comment]
So the conclution is that we can't. Maybe this feature will be added in the future...
